[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Bruno Ricci"]
edition = "2018"

[dependencies]
jsonwebtoken = "5"
serde_derive = "1"
serde = "1"
ring = "0.13.5"
untrusted = "0.6.2"
rand = "0.6.0"
reqwest = "0.9.9"